version: '3.8'

services:
  db:
    image: postgres:12-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '6060:5432'

volumes:
  db-data:
    driver: local
